-- MySQL Script generated by MySQL Workbench
-- Qua 14 Set 2016 22:19:39 BRT
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema carros
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema carros
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `carros` DEFAULT CHARACTER SET latin1 ;
USE `carros` ;

-- -----------------------------------------------------
-- Table `carros`.`campeonato`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `carros`.`campeonato` (
  `cam_codigo` INT NOT NULL,
  `cam_descricao` VARCHAR(100) NULL,
  `cam_data_inicial` DATETIME NULL,
  `cam_data_final` DATETIME NULL,
  PRIMARY KEY (`cam_codigo`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;

ALTER TABLE `campeonato`
  MODIFY `cam_codigo` int(11) NOT NULL AUTO_INCREMENT;

-- -----------------------------------------------------
-- Table `carros`.`piloto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `carros`.`piloto` (
  `pil_codigo` INT NOT NULL,
  `pil_data_nascimento` INT NULL,
  `pil_uf_naturalidade` CHAR(2) NULL,
  `pil_cpf` VARCHAR(11) NULL,
  `pil_nome` VARCHAR(100) NULL,
  PRIMARY KEY (`pil_codigo`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;

ALTER TABLE `piloto`
  MODIFY `pil_codigo` int(11) NOT NULL AUTO_INCREMENT;
-- -----------------------------------------------------
-- Table `carros`.`veiculo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `carros`.`veiculo` (
  `vei_codigo` INT NOT NULL,
  `vei_marca` VARCHAR(30) NULL,
  `vei_modelo` VARCHAR(20) NULL,
  `vei_ano` INT NULL,
  `vei_velocidade_max` DECIMAL(18,2) NULL,
  `vei_placa` VARCHAR(45) NULL,
  `piloto_pil_codigo` INT NOT NULL,
  PRIMARY KEY (`vei_codigo`),
  INDEX `fk_veiculo_piloto_idx` (`piloto_pil_codigo` ASC),
  CONSTRAINT `fk_veiculo_piloto`
    FOREIGN KEY (`piloto_pil_codigo`)
    REFERENCES `carros`.`piloto` (`pil_codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;

ALTER TABLE `veiculo`
  MODIFY `vei_codigo` int(11) NOT NULL AUTO_INCREMENT;

-- -----------------------------------------------------
-- Table `carros`.`corrida`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `carros`.`corrida` (
  `cor_codigo` INT NOT NULL,
  `cor_data` DATE NULL,
  `cor_hora` TIME NULL,
  `cor_descricao` VARCHAR(100) NULL,
  PRIMARY KEY (`cor_codigo`))
ENGINE = InnoDB;

ALTER TABLE `corrida`
  MODIFY `cor_codigo` int(11) NOT NULL AUTO_INCREMENT;

-- -----------------------------------------------------
-- Table `carros`.`venda_ingresso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `carros`.`venda_ingresso` (
  `ven_codigo` INT NOT NULL,
  `ven_valor` DECIMAL(18,2) NULL,
  `ven_quantidade_max` INT NULL,
  `cor_codigo` INT NOT NULL,
  PRIMARY KEY (`ven_codigo`),
  INDEX `fk_venda_ingresso_corrida1_idx` (`cor_codigo` ASC),
  CONSTRAINT `fk_venda_ingresso_corrida1`
    FOREIGN KEY (`cor_codigo`)
    REFERENCES `carros`.`corrida` (`cor_codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

ALTER TABLE `venda_ingresso`
  MODIFY `ven_codigo` int(11) NOT NULL AUTO_INCREMENT;

-- -----------------------------------------------------
-- Table `carros`.`ingresso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `carros`.`ingresso` (
  `ing_codigo` INT NOT NULL,
  `ing_valor` VARCHAR(45) NULL,
  `ven_codigo` INT NOT NULL,
  PRIMARY KEY (`ing_codigo`),
  INDEX `fk_ingresso_venda_ingresso1_idx` (`ven_codigo` ASC),
  CONSTRAINT `fk_ingresso_venda_ingresso1`
    FOREIGN KEY (`ven_codigo`)
    REFERENCES `carros`.`venda_ingresso` (`ven_codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;

ALTER TABLE `ingresso`
  MODIFY `ing_codigo` int(11) NOT NULL AUTO_INCREMENT;

-- -----------------------------------------------------
-- Table `carros`.`patrocinador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `carros`.`patrocinador` (
  `pat_codigo` INT NOT NULL,
  `pat_cnpj` VARCHAR(14) NULL,
  `pat_nome` VARCHAR(45) NULL,
  PRIMARY KEY (`pat_codigo`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;

ALTER TABLE `patrocinador`
  MODIFY `pat_codigo` int(11) NOT NULL AUTO_INCREMENT;

-- -----------------------------------------------------
-- Table `carros`.`equipe`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `carros`.`equipe` (
  `eqp_codigo` INT NOT NULL,
  `eqp_nome` VARCHAR(100) NULL,
  `eqp_data_formacao` DATE NULL,
  PRIMARY KEY (`eqp_codigo`))
ENGINE = InnoDB;

ALTER TABLE `equipe`
  MODIFY `eqp_codigo` int(11) NOT NULL AUTO_INCREMENT;

-- -----------------------------------------------------
-- Table `carros`.`piloto_equipe`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `carros`.`piloto_equipe` (
  `pil_codigo` INT NOT NULL,
  `eqp_codigo` INT NOT NULL,
  `peq_codigo` INT NOT NULL,
  PRIMARY KEY (`pil_codigo`, `peq_codigo`),
  INDEX `fk_piloto_has_equipe_equipe1_idx` (`eqp_codigo` ASC),
  INDEX `fk_piloto_has_equipe_piloto1_idx` (`pil_codigo` ASC),
  CONSTRAINT `fk_piloto_has_equipe_piloto1`
    FOREIGN KEY (`pil_codigo`)
    REFERENCES `carros`.`piloto` (`pil_codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_piloto_has_equipe_equipe1`
    FOREIGN KEY (`eqp_codigo`)
    REFERENCES `carros`.`equipe` (`eqp_codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `carros`.`patrocinio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `carros`.`patrocinio` (
  `eqp_codigo` INT NOT NULL,
  `pat_codigo` INT NOT NULL,
  `peq_valor_investimento` DECIMAL(18,2) NULL,
  `pat_data_inicial` DATETIME NULL,
  `pat_data_final` DATETIME NULL,
  PRIMARY KEY (`eqp_codigo`, `pat_codigo`),
  INDEX `fk_equipe_has_patrocinador_patrocinador1_idx` (`pat_codigo` ASC),
  INDEX `fk_equipe_has_patrocinador_equipe1_idx` (`eqp_codigo` ASC),
  CONSTRAINT `fk_equipe_has_patrocinador_equipe1`
    FOREIGN KEY (`eqp_codigo`)
    REFERENCES `carros`.`equipe` (`eqp_codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_equipe_has_patrocinador_patrocinador1`
    FOREIGN KEY (`pat_codigo`)
    REFERENCES `carros`.`patrocinador` (`pat_codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `carros`.`piloto_corrida`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `carros`.`piloto_corrida` (
  `pil_codigo` INT NOT NULL,
  `cor_codigo` INT NOT NULL,
  `pic_posicao_largada` INT NULL,
  `pic_posicao_chegada` INT NULL,
  `pic_pontuacao` DECIMAL(18,2) NULL,
  `pic_codigo` INT(11) NOT NULL,
  PRIMARY KEY (`cor_codigo`, `pic_codigo`, `pil_codigo`),
  INDEX `fk_piloto_has_corrida_corrida1_idx` (`cor_codigo` ASC),
  INDEX `fk_piloto_has_corrida_piloto1_idx` (`pil_codigo` ASC),
  CONSTRAINT `fk_piloto_has_corrida_piloto1`
    FOREIGN KEY (`pil_codigo`)
    REFERENCES `carros`.`piloto` (`pil_codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_piloto_has_corrida_corrida1`
    FOREIGN KEY (`cor_codigo`)
    REFERENCES `carros`.`corrida` (`cor_codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `carros`.`autodromo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `carros`.`autodromo` (
  `aut_codigo` INT NOT NULL,
  `aut_descricao` VARCHAR(100) NULL,
  `aut_nome_pista` VARCHAR(100) NULL,
  `aut_uf` CHAR(2) NULL,
  `aut_cidade` VARCHAR(100) NULL,
  PRIMARY KEY (`aut_codigo`))
ENGINE = InnoDB;

ALTER TABLE `autodromo`
  MODIFY `aut_codigo` int(11) NOT NULL AUTO_INCREMENT;


-- -----------------------------------------------------
-- Table `carros`.`campeonato_nacional`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `carros`.`campeonato_nacional` (
  `cam_codigo` INT NOT NULL,
  `can_codigo_nacional` VARCHAR(8) NULL,
  `can_nbr` VARCHAR(45) NULL,
  INDEX `fk_campeonato_nacional_campeonato1_idx` (`cam_codigo` ASC),
  PRIMARY KEY (`cam_codigo`),
  CONSTRAINT `fk_campeonato_nacional_campeonato1`
    FOREIGN KEY (`cam_codigo`)
    REFERENCES `carros`.`campeonato` (`cam_codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `carros`.`campeonato_internacional`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `carros`.`campeonato_internacional` (
  `cam_codigo` INT NOT NULL,
  `cai_codigo_internacional` VARCHAR(15) NULL,
  `cai_iec` VARCHAR(45) NULL,
  INDEX `fk_campeonato_internacional_campeonato1_idx` (`cam_codigo` ASC),
  PRIMARY KEY (`cam_codigo`),
  CONSTRAINT `fk_campeonato_internacional_campeonato1`
    FOREIGN KEY (`cam_codigo`)
    REFERENCES `carros`.`campeonato` (`cam_codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `carros`.`corrida_campeonato`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `carros`.`corrida_campeonato` (
  `cor_codigo` INT NOT NULL,
  `cam_codigo` INT NOT NULL,
  `aut_codigo` INT NOT NULL,
  PRIMARY KEY (`cor_codigo`, `cam_codigo`),
  INDEX `fk_corrida_has_campeonato_campeonato1_idx` (`cam_codigo` ASC),
  INDEX `fk_corrida_has_campeonato_corrida1_idx` (`cor_codigo` ASC),
  INDEX `fk_corrida_campeonato_autodromo1_idx` (`aut_codigo` ASC),
  CONSTRAINT `fk_corrida_has_campeonato_corrida1`
    FOREIGN KEY (`cor_codigo`)
    REFERENCES `carros`.`corrida` (`cor_codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_corrida_has_campeonato_campeonato1`
    FOREIGN KEY (`cam_codigo`)
    REFERENCES `carros`.`campeonato` (`cam_codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_corrida_campeonato_autodromo1`
    FOREIGN KEY (`aut_codigo`)
    REFERENCES `carros`.`autodromo` (`aut_codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
